server:
  port: 8073
spring:
  application:
    name: "storeServer"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          serverId: "storeServer1"
  datasource:
    url: "jdbc:mysql://localhost:3306/bucketworld"
    username: "root"
    password: "123456"
myapp:
  greeting: Hello from the configuration file!
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN


