logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
server:
  port: 8070
spring:
  application:
    name: "client"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



